apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deployment
# Deployment Specific Specifications.
spec:
  replicas: 1 
  # This section (selector) actually tells the deployment specified above about: Which pods belong to deployment.
  selector:
    # MatchLabels: Add the key/value pairs that belong to deployment.
    matchLabels:
      app: k8s-demo
  # This defines the configuration for Pod (has its own metadata and spec) within the deployment.
  template:
    metadata:
      # Beauty: Labels are shared among pods.
      # In other words, replicas of pods won't need to be addressed individually and instead can be referred to using a single label.
      labels:
        app: k8s-demo
    # List of containers that are meant to be run in this pod.
    spec:
      containers:
      - name: k8s-demo
        image: k8s_demo:v1  # This is the tag (name:label) of the image you have locally. Images existing in remote repositories can also be used.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000  # Port at which our container will listen (MongoDB by default uses 27017).
        resources:
          requests:
            memory: 320M
            cpu: 50m
          limits:
            memory: 640M
            cpu: 100m
