apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-service
  namespace: default  # 
  labels:
    app: k8s-demo
spec:
  type: NodePort  # By Default this is ClusterIP: Meant to be used as an internel service.
  ports:
  - port: 4000
    targetPort: 4000 # The port of the pod (Must match the container port defined for pod).
                     #  Note: Keeping both port and targetPort same is a good practice for simplicity.
    nodePort: 30001  # Exposes the Service on each Node's IP at a static port mentioned here.
                     # Note: Nodeport has a dedicated range and cannot be set arbitrarily.
    protocol: TCP
    name: k8s-demo-http
  selector:
    app: k8s-demo